/* 
1.To compile the java code we need a tool and that tool is known as JDK(java developement kit).
-Byte code run on a machine so we have to convert java code into byte code
2. JVM stands for java virtual machine.
-jvm is the space where you execute the code.
-you have to compile the code through JDK and then run the code through JVM .
-JVM is platform dependent
3. JRE stands for java runtime environment.
-JRE contain all in-built classes and other extra file that we can use in our code.
-JRE validate the byte code
4. for developement purposes ,you need to install JDK which consist of JRE and JVM.
